### ISSUE TITLE
T-Rax crashes after mousewheel is used in intensity vs wavelength graphs

### ISSUE THREAD

**Issue by erangre** [Luindil/T-rax#8]
The problem occurs after the update to PyQt5 (and qtpy).
After using mousewheel (with no effect since it is disabled there) on the two panels showing US and DS intensity vs wavelength, and moving out of the panels, the software crashes.
It is possible to fix this in ModifiedPlotItem by removing the if clause in modify_mouse_behavior.
However, then it is possible to zoom in and out of the graphs and they do not autoscale nicely.
Have not found a way to keep these settings and fix this at the same time.

**Comment by CPrescher** [comment]
This was due to some other parameters send to the dummy, function, I added dummy variables and now it works...
